local a = ptr.seedP()
assert(ptr.geneP(a) == a)
assert(ptr.intP(a) == a)
assert(ptr.genePA(a) == a)
assert(ptr.intPA(a) == a)
assert(ptr.genePPA(a) == a)
assert(ptr.intPPA(a) == a)
assert(ptr.genePPB(a) == a)
assert(ptr.intPPB(a) == a)